### ISSUE TITLE
PathBuf and OsStr use - not String

### ISSUE THREAD

**Issue by jrgerber** [jrgerber/dmidecode-rs#25]
There are some functions which take file paths as Strings.  These should probably be using PathBuf and OsStr.  Different OS's treat paths differently with \ or / for example and possibly some characters are invalid between them.

Review the existing API's that DMIDECODE uses for file paths from smbios-lib and make them both use proper types to describe paths.

https://doc.rust-lang.org/std/path/struct.PathBuf.html
https://doc.rust-lang.org/std/ffi/struct.OsString.html

**Comment by jczuluag** [comment]
@jrgerber , are these functions consumed by dmidecode-rs? If that is the case should be this bug move to the lib repo?

**Comment by jrgerber** [comment]
> @jrgerber , are these functions consumed by dmidecode-rs? If that is the case should be this bug move to the lib repo?

Yes, and that will create work here too.

I noticed structopt was using PathBuf when reading from the command line.  Path::from_string() I think knows to accept \ or / .  The branch I am working in on smbios-lib I've started playing with using Path.  The reason is cross-platform compatibility and accepting things which are paths and not just any string.

**Comment by jczuluag** [comment]
> > @jrgerber , are these functions consumed by dmidecode-rs? If that is the case should be this bug move to the lib repo?
> 
> Yes, and that will create work here too.
> 
> I noticed structopt was using PathBuf when reading from the command line. Path::from_string() I think knows to accept \ or / . The branch I am working in on smbios-lib I've started playing with using Path. The reason is cross-platform compatibility and accepting things which are paths and not just any string.

Cool, I opened: https://github.com/jrgerber/smbios-lib/issues/47
