### ISSUE TITLE
Implement --oem-string N

### ISSUE THREAD

**Issue by jrgerber** [jrgerber/dmidecode-rs#27]
--oem-string N
              Only display the value of the OEM string number N. The first OEM
              string has number 1. With special value "count", return the
              number of OEM strings instead.

Investigate how it is implemented here: https://github.com/mirror/dmidecode/blob/master/dmidecode.c

**Comment by jczuluag** [comment]
@jrgerber, looking at the spec, this is OEM Strings (Type 11) struct. Wondering if the right approach would be to get this type and then handle whether is `N` or `count`?

**Comment by jrgerber** [comment]
> @jrgerber, looking at the spec, this is OEM Strings (Type 11) struct. Wondering if the right approach would be to get this type and then handle whether is `N` or `count`?

That sounds correct.  I imagine this might be used at large companies, for example they have devices like HP or Dell and then they know what will be at OEM string 3 and they collect from all the devices?
