### ISSUE TITLE
Add tests for new CL options

### ISSUE THREAD

**Issue by jrgerber** [jrgerber/dmidecode-rs#30]
I added new options and had not added tests paired with them after the new dependencies for CLI testing were added to the project.

Currently working on two new options for the CLI so this work can be either done as part of that or afterwards.  So this work is to add whatever missing CLI tests exist.

**Comment by jczuluag** [comment]
@jrgerber , do you recall which new command line options you refer here?

**Comment by jrgerber** [comment]
> @jrgerber , do you recall which new command line options you refer here? `-H` and `-u` ?

Yes, exactly!
