### ISSUE TITLE
--no-sysfs prints json

### ISSUE THREAD

**Issue by mulark** [jrgerber/dmidecode-rs#52]
We should just be printing the same thing dmidecode does when this arg is supplied.

**Comment by jrgerber** [comment]
Absolutely.

This project's goals are:
1. To give users of the official/original dmidecode an experience of equal parity for existing functionalities.
2. Add new useful features based on customer requests (e.g. JSON) so long as they don't interfere with goal number 1.

Clarifications about the goals:
- People have written scripts that consume the output of dmidecode and these scripts must not break when using dmidecode-rs.
- The customer feature requests / issues found on https://github.com/mirror/dmidecode are a good read and a source of feature ideas.  The JSON request (https://github.com/mirror/dmidecode/issues/4) was one of these.  It was cost effective to create in Rust and would be quite expensive in C.
- This project will _follow_ changes made on the original dmidecode to maintain parity.  For example, recently the DMTF SMBIOS 3.5 standard was released and dmidecode was updated accordingly.
